/**
 * @file    m8_alarm_sw_table.h
 * @brief   M8 机型调用点触发报警目录
 * @author  HUWANGWEI
 * @date    2026-07-09
 */

#ifndef CONFIG_MACHINE_M8_SW_ALARM_TABLE_H
#define CONFIG_MACHINE_M8_SW_ALARM_TABLE_H

#include "framework/domain/safety/model/alarm_types.h"
#include "projects/m8/config/m8_alarm_table.h"

/**
 * @brief  调用点触发报警总表
 *
 * 列：class, index, nature, level, response, clear, source_kind, scope, desc
 */
#define M8_SW_ALARM_TABLE(X) \
    X(ALM_C_CTRL, ALM_CTRL_VOICE,  ALM_N_COMM_LOST, \
      ALARM_LEVEL_MINOR, RESP_LOG_ONLY, ALARM_CLEAR_MANUAL_RESET, \
      ALARM_SOURCE_COMM, ALARM_SCOPE_NONE, "语音模块通讯失败") \
    X(ALM_C_SENSE, ALM_SENSE_GANTRY_ENC,     ALM_N_SIG_ERR, \
      ALARM_LEVEL_MAJOR, RESP_COMPLETE_THEN_ASSESS, ALARM_CLEAR_ON_MOTION, \
      ALARM_SOURCE_PROCESS, ALARM_SCOPE_GANTRY, "龙门码盘行走无脉冲") \
    X(ALM_C_SENSE, ALM_SENSE_GANTRY_FWD_LIM, ALM_N_TIMEOUT, \
      ALARM_LEVEL_MAJOR, RESP_COMPLETE_THEN_ASSESS, ALARM_CLEAR_ON_MOTION, \
      ALARM_SOURCE_PROCESS, ALARM_SCOPE_GANTRY, "龙门前限位动作超时") \
    X(ALM_C_SENSE, ALM_SENSE_GANTRY_REV_LIM, ALM_N_TIMEOUT, \
      ALARM_LEVEL_MAJOR, RESP_COMPLETE_THEN_ASSESS, ALARM_CLEAR_ON_MOTION, \
      ALARM_SOURCE_PROCESS, ALARM_SCOPE_GANTRY, "龙门后限位动作超时") \
    X(ALM_C_SENSE, ALM_SENSE_TOP_BRUSH_UP_LIM, ALM_N_TIMEOUT, \
      ALARM_LEVEL_MAJOR, RESP_COMPLETE_THEN_ASSESS, ALARM_CLEAR_ON_MOTION, \
      ALARM_SOURCE_PROCESS, ALARM_SCOPE_TOP_BRUSH, "顶刷上限位动作超时") \
    X(ALM_C_SENSE, ALM_SENSE_TOP_BRUSH_DN_LIM, ALM_N_TIMEOUT, \
      ALARM_LEVEL_MAJOR, RESP_COMPLETE_THEN_ASSESS, ALARM_CLEAR_ON_MOTION, \
      ALARM_SOURCE_PROCESS, ALARM_SCOPE_TOP_BRUSH, "顶刷下限位动作超时") \
    X(ALM_C_SENSE, ALM_SENSE_TOP_BRUSH_POT,    ALM_N_SIG_ERR, \
      ALARM_LEVEL_MAJOR, RESP_COMPLETE_THEN_ASSESS, ALARM_CLEAR_ON_MOTION, \
      ALARM_SOURCE_PROCESS, ALARM_SCOPE_TOP_BRUSH, "顶刷推杆电位计读数异常") \
    X(ALM_C_SENSE, ALM_SENSE_TOP_BRUSH_SW,     ALM_N_SIG_ERR, \
      ALARM_LEVEL_MAJOR, RESP_COMPLETE_THEN_ASSESS, ALARM_CLEAR_ON_MOTION, \
      ALARM_SOURCE_PROCESS, ALARM_SCOPE_TOP_BRUSH, "顶刷切换开关状态不一致") \
    X(ALM_C_SENSE, ALM_SENSE_SIDE_BRUSH_SW,    ALM_N_SIG_ERR, \
      ALARM_LEVEL_MAJOR, RESP_COMPLETE_THEN_ASSESS, ALARM_CLEAR_ON_MOTION, \
      ALARM_SOURCE_PROCESS, ALARM_SCOPE_SIDE_BRUSH, "侧刷切换开关状态不一致") \
    X(ALM_C_SENSE, ALM_SENSE_HEIGHT_RADAR,     ALM_N_SIG_ERR, \
      ALARM_LEVEL_MAJOR, RESP_COMPLETE_THEN_ASSESS, ALARM_CLEAR_MANUAL_RESET, \
      ALARM_SOURCE_PROCESS, ALARM_SCOPE_NONE, "高度测距雷达信号异常") \
    X(ALM_C_SENSE, ALM_SENSE_FRONT_WHEEL_OPT,  ALM_N_SIG_ERR, \
      ALARM_LEVEL_MAJOR, RESP_COMPLETE_THEN_ASSESS, ALARM_CLEAR_ON_MOTION, \
      ALARM_SOURCE_PROCESS, ALARM_SCOPE_FRONT_WHEEL, "前轮检测光电状态异常") \
    X(ALM_C_SENSE, ALM_SENSE_REAR_WHEEL_OPT,   ALM_N_SIG_ERR, \
      ALARM_LEVEL_MAJOR, RESP_COMPLETE_THEN_ASSESS, ALARM_CLEAR_ON_MOTION, \
      ALARM_SOURCE_PROCESS, ALARM_SCOPE_REAR_WHEEL_LOCK, "后轮锁紧光电状态异常") \
    X(ALM_C_SENSE, ALM_SENSE_REAR_LOCK_HOME,   ALM_N_TIMEOUT, \
      ALARM_LEVEL_MAJOR, RESP_COMPLETE_THEN_ASSESS, ALARM_CLEAR_ON_MOTION, \
      ALARM_SOURCE_PROCESS, ALARM_SCOPE_REAR_WHEEL_LOCK, "后轮锁紧机构原点动作超时") \
    X(ALM_C_SW, ALM_SW_USER_STOP, ALM_N_OTHER, \
      ALARM_LEVEL_MINOR, RESP_LOG_ONLY, ALARM_CLEAR_AUTO_STATIC, \
      ALARM_SOURCE_CALLSITE, ALARM_SCOPE_NONE, "用户主动停止")

#endif /* CONFIG_MACHINE_M8_SW_ALARM_TABLE_H */
