/**
 * @file    m8_alarm_table.h
 * @brief   M8 机型报警配置表（DI + 防抖 + 报警码 + 等级 + 描述）
 * @author  HUWANGWEI
 * @date    2026-07-09
 */

#ifndef CONFIG_MACHINE_M8_ALARM_TABLE_H
#define CONFIG_MACHINE_M8_ALARM_TABLE_H

#include "framework/domain/safety/model/alarm_types.h"
#include "projects/m8/config/m8_io_pins.h"

#define ALM_POWER_GANTRY_MOTOR      1U
#define ALM_POWER_TOP_BRUSH_ROT     2U
#define ALM_POWER_TOP_BRUSH_LIFT    3U
#define ALM_POWER_SIDE_BRUSH        4U
#define ALM_POWER_FAN               5U

#define ALM_SENSE_GANTRY_ENC         1U
#define ALM_SENSE_GANTRY_FWD_LIM     2U
#define ALM_SENSE_GANTRY_REV_LIM     3U

/** @brief 龙门流程报警码（供 gantry.c 与目录表编译期校验） */
#define M8_GANTRY_ALM_ENC_ERR \
    ALARM_CODE_MAKE(ALM_C_SENSE, ALM_SENSE_GANTRY_ENC, ALM_N_SIG_ERR)
#define M8_GANTRY_ALM_FWD_TMO \
    ALARM_CODE_MAKE(ALM_C_SENSE, ALM_SENSE_GANTRY_FWD_LIM, ALM_N_TIMEOUT)
#define M8_GANTRY_ALM_REV_TMO \
    ALARM_CODE_MAKE(ALM_C_SENSE, ALM_SENSE_GANTRY_REV_LIM, ALM_N_TIMEOUT)

#define M8_TOP_BRUSH_LIFT_ALM_UP_TMO \
    ALARM_CODE_MAKE(ALM_C_SENSE, ALM_SENSE_TOP_BRUSH_UP_LIM, ALM_N_TIMEOUT)
#define M8_TOP_BRUSH_LIFT_ALM_DN_TMO \
    ALARM_CODE_MAKE(ALM_C_SENSE, ALM_SENSE_TOP_BRUSH_DN_LIM, ALM_N_TIMEOUT)

#define ALM_SENSE_TOP_BRUSH_UP_LIM   4U
#define ALM_SENSE_TOP_BRUSH_DN_LIM   5U
#define ALM_SENSE_TOP_BRUSH_POT      6U
#define ALM_SENSE_TOP_BRUSH_BUMPER   7U
#define ALM_SENSE_TOP_BRUSH_SW       8U
#define ALM_SENSE_TOP_BRUSH_OVL      9U
#define ALM_SENSE_SIDE_BRUSH_SW      10U
#define ALM_SENSE_SIDE_BRUSH_OVL     11U
#define ALM_SENSE_HEIGHT_RADAR       12U
#define ALM_SENSE_BUMPER_LEFT        13U
#define ALM_SENSE_BUMPER_ROD_LEFT    14U
#define ALM_SENSE_BUMPER_RIGHT       15U
#define ALM_SENSE_BUMPER_ROD_RIGHT   16U
#define ALM_SENSE_ESTOP              17U

#define M8_ALARM_CODE_ESTOP \
    ALARM_CODE_MAKE(ALM_C_SENSE, ALM_SENSE_ESTOP, ALM_N_SAFETY)

#define ALM_SENSE_FRONT_WHEEL_OPT    18U
#define ALM_SENSE_REAR_WHEEL_OPT     19U
#define ALM_SENSE_REAR_LOCK_HOME     20U
#define ALM_SENSE_FOAM_LEVEL         21U
#define ALM_SENSE_WAX_LEVEL          22U
#define ALM_SENSE_PUMP_OVL           23U

#define ALM_ACT_TOP_BRUSH_CONTACTOR   1U
#define ALM_ACT_SIDE_BRUSH_CONTACTOR  2U
#define ALM_ACT_PUMP_CONTACTOR        3U

#define ALM_CTRL_GANTRY_VFD    1U
#define ALM_CTRL_BRUSH_VFD     2U
#define ALM_CTRL_FAN_VFD       3U
#define ALM_CTRL_IO_BOARD      4U
#define ALM_CTRL_VOICE         5U

#define ALM_SW_USER_STOP       1U

/**
 * @brief  DI 硬件报警总表
 *
 * 列：pin, active_low, trig_max, rel_max, class, index, nature,
 *     level, response, clear, source_kind, reeval_group, immediate_cutout, desc
 */
#define M8_HW_ALARM_TABLE(X) \
    X(M8_IO_DI_ESTOP,               true,  1U, 3U, \
      ALM_C_SENSE, ALM_SENSE_ESTOP,            ALM_N_SAFETY,   \
      ALARM_LEVEL_CRITICAL, RESP_STOP_IMMEDIATELY, ALARM_CLEAR_AUTO_STATIC, \
      ALARM_SOURCE_LEVEL, ALARM_REEVAL_GROUP_NONE, false, "急停按钮触发") \
    X(M8_IO_DI_TOP_BRUSH_COLLISION, true,  1U, 3U, \
      ALM_C_SENSE, ALM_SENSE_TOP_BRUSH_BUMPER, ALM_N_SAFETY,   \
      ALARM_LEVEL_CRITICAL, RESP_STOP_IMMEDIATELY, ALARM_CLEAR_AUTO_STATIC, \
      ALARM_SOURCE_LEVEL, ALARM_REEVAL_GROUP_NONE, false, "顶刷防撞触发") \
    X(M8_IO_DI_BUMPER_LEFT,         true,  1U, 3U, \
      ALM_C_SENSE, ALM_SENSE_BUMPER_LEFT,      ALM_N_SAFETY,   \
      ALARM_LEVEL_CRITICAL, RESP_STOP_IMMEDIATELY, ALARM_CLEAR_AUTO_STATIC, \
      ALARM_SOURCE_LEVEL, ALARM_REEVAL_GROUP_NONE, false, "左防撞胶条触发") \
    X(M8_IO_DI_BUMPER_ROD_LEFT,     true,  1U, 3U, \
      ALM_C_SENSE, ALM_SENSE_BUMPER_ROD_LEFT,  ALM_N_SAFETY,   \
      ALARM_LEVEL_CRITICAL, RESP_STOP_IMMEDIATELY, ALARM_CLEAR_AUTO_STATIC, \
      ALARM_SOURCE_LEVEL, ALARM_REEVAL_GROUP_NONE, false, "左防撞杆触发") \
    X(M8_IO_DI_BUMPER_RIGHT,        true,  1U, 3U, \
      ALM_C_SENSE, ALM_SENSE_BUMPER_RIGHT,     ALM_N_SAFETY,   \
      ALARM_LEVEL_CRITICAL, RESP_STOP_IMMEDIATELY, ALARM_CLEAR_AUTO_STATIC, \
      ALARM_SOURCE_LEVEL, ALARM_REEVAL_GROUP_NONE, false, "右防撞胶条触发") \
    X(M8_IO_DI_BUMPER_ROD_RIGHT,    true,  1U, 3U, \
      ALM_C_SENSE, ALM_SENSE_BUMPER_ROD_RIGHT, ALM_N_SAFETY,   \
      ALARM_LEVEL_CRITICAL, RESP_STOP_IMMEDIATELY, ALARM_CLEAR_AUTO_STATIC, \
      ALARM_SOURCE_LEVEL, ALARM_REEVAL_GROUP_NONE, false, "右防撞杆触发") \
    X(M8_IO_DI_TOP_BRUSH_OVERLOAD,  false, 3U, 3U, \
      ALM_C_SENSE, ALM_SENSE_TOP_BRUSH_OVL,    ALM_N_OVERLOAD, \
      ALARM_LEVEL_MAJOR, RESP_COMPLETE_THEN_ASSESS, ALARM_CLEAR_MANUAL_RESET, \
      ALARM_SOURCE_LEVEL, ALARM_REEVAL_GROUP_NONE, false, "顶刷电机过载") \
    X(M8_IO_DI_SIDE_BRUSH_OVERLOAD, false, 3U, 3U, \
      ALM_C_SENSE, ALM_SENSE_SIDE_BRUSH_OVL,   ALM_N_OVERLOAD, \
      ALARM_LEVEL_MAJOR, RESP_COMPLETE_THEN_ASSESS, ALARM_CLEAR_MANUAL_RESET, \
      ALARM_SOURCE_LEVEL, ALARM_REEVAL_GROUP_NONE, false, "侧刷电机过载") \
    X(M8_IO_DI_WATER_PUMP_OVERLOAD, false, 3U, 3U, \
      ALM_C_SENSE, ALM_SENSE_PUMP_OVL,         ALM_N_OVERLOAD, \
      ALARM_LEVEL_MAJOR, RESP_COMPLETE_THEN_ASSESS, ALARM_CLEAR_MANUAL_RESET, \
      ALARM_SOURCE_LEVEL, ALARM_REEVAL_GROUP_NONE, false, "水泵过载") \
    X(M8_IO_DI_GANTRY_ALARM,        false, 3U, 3U, \
      ALM_C_CTRL,  ALM_CTRL_GANTRY_VFD,       ALM_N_HW_FAULT, \
      ALARM_LEVEL_CRITICAL, RESP_STOP_IMMEDIATELY, ALARM_CLEAR_MANUAL_RESET, \
      ALARM_SOURCE_LEVEL, ALARM_REEVAL_GROUP_NONE, false, "龙门变频器报警反馈") \
    X(M8_IO_DI_BRUSH_ALARM,         false, 3U, 3U, \
      ALM_C_CTRL,  ALM_CTRL_BRUSH_VFD,        ALM_N_HW_FAULT, \
      ALARM_LEVEL_MAJOR, RESP_COMPLETE_THEN_ASSESS, ALARM_CLEAR_MANUAL_RESET, \
      ALARM_SOURCE_LEVEL, ALARM_REEVAL_GROUP_NONE, false, "侧刷变频器报警反馈") \
    X(M8_IO_DI_FAN_ALARM,           false, 3U, 3U, \
      ALM_C_CTRL,  ALM_CTRL_FAN_VFD,          ALM_N_HW_FAULT, \
      ALARM_LEVEL_MINOR, RESP_LOG_ONLY, ALARM_CLEAR_AUTO_STATIC, \
      ALARM_SOURCE_LEVEL, ALARM_REEVAL_GROUP_NONE, false, "风机报警反馈")

#endif /* CONFIG_MACHINE_M8_ALARM_TABLE_H */
