#ifndef SHARED_ERROR_CODES_H
#define SHARED_ERROR_CODES_H

/**
 * @file error_codes.h
 * @brief 定义主控软件统一错误码。
 */

typedef enum {
    ERROR_CODE_OK = 0,
    ERROR_CODE_INVALID_ARGUMENT,
    ERROR_CODE_INVALID_STATE,
    ERROR_CODE_PRECHECK_FAILED,
    ERROR_CODE_VEHICLE_NOT_ALLOWED,
    ERROR_CODE_SAFETY_INTERLOCK_ACTIVE,
    ERROR_CODE_RESOURCE_UNAVAILABLE,
    ERROR_CODE_TIMEOUT,
    ERROR_CODE_PARSE_FAILED,
    ERROR_CODE_IO_FAILED,
    ERROR_CODE_UNSUPPORTED
} error_code_t;

#endif

