#ifndef DOMAIN_MODEL_DOMAIN_ENUMS_H
#define DOMAIN_MODEL_DOMAIN_ENUMS_H

#include <stdbool.h>

typedef enum {
    GANTRY_MOTION_STOP = 0,
    GANTRY_MOTION_FORWARD,
    GANTRY_MOTION_REVERSE,
    GANTRY_MOTION_TRAVERSE
} gantry_motion_mode_t;

typedef enum {
    BRUSH_MODE_DISABLED = 0,
    BRUSH_MODE_FOLLOW,
    BRUSH_MODE_FIXED
} brush_mode_t;

typedef enum {
    CHEMICAL_START_ON_STAGE_START = 0,
    CHEMICAL_START_ON_POSITION_REACHED,
    CHEMICAL_START_MID_STAGE
} chemical_start_condition_t;

typedef enum {
    RESOURCE_STATE_NORMAL = 0,
    RESOURCE_STATE_LOW,
    RESOURCE_STATE_FAULT,
    RESOURCE_STATE_DISABLED
} resource_state_t;

typedef enum {
    FAULT_POLICY_DEGRADE = 0,
    FAULT_POLICY_SKIP,
    FAULT_POLICY_SAFE_FINISH
} fault_policy_t;

typedef enum {
    CYCLE_STATE_IDLE = 0,
    CYCLE_STATE_PRECHECK,
    CYCLE_STATE_RUNNING,
    CYCLE_STATE_DEGRADED,
    CYCLE_STATE_SAFE_STOP,
    CYCLE_STATE_COMPLETED,
    CYCLE_STATE_ABORTED
} cycle_state_t;

typedef enum {
    RESULT_CODE_SUCCESS = 0,
    RESULT_CODE_SAFE_STOP,
    RESULT_CODE_DEGRADED_COMPLETE,
    RESULT_CODE_MANUAL_ABORT,
    RESULT_CODE_START_FAILED
} result_code_t;

typedef enum {
    FAULT_SEVERITY_INFO = 0,
    FAULT_SEVERITY_WARNING,
    FAULT_SEVERITY_SAFETY
} fault_severity_t;

typedef enum {
    FAULT_CLASS_SAFETY = 0,
    FAULT_CLASS_PROCESS,
    FAULT_CLASS_RESOURCE,
    FAULT_CLASS_COMMUNICATION,
    FAULT_CLASS_CONFIGURATION
} fault_class_t;

typedef enum {
    INTERLOCK_READY = 0,
    INTERLOCK_TRIPPED,
    INTERLOCK_BYPASSED
} interlock_state_t;

typedef enum {
    TRIP_ACTION_BLOCK_START = 0,
    TRIP_ACTION_STOP_IMMEDIATELY
} trip_action_t;

typedef enum {
    RESET_RULE_AUTO = 0,
    RESET_RULE_MANUAL
} reset_rule_t;

typedef enum {
    EVENT_TYPE_CYCLE_STATE_CHANGED = 0,
    EVENT_TYPE_FAULT_RAISED,
    EVENT_TYPE_FAULT_CLEARED,
    EVENT_TYPE_CYCLE_FINISHED
} event_type_t;

typedef enum {
    SESSION_STATE_NONE = 0,
    SESSION_STATE_CREATED,
    SESSION_STATE_RUNNING,
    SESSION_STATE_COMPLETED,
    SESSION_STATE_ABORTED
} session_state_t;

typedef enum {
    EXECUTION_STATE_NONE = 0,
    EXECUTION_STATE_RUNNING,
    EXECUTION_STATE_COMPLETED,
    EXECUTION_STATE_ABORTED
} execution_state_t;

typedef enum {
    EXECUTION_KIND_STAGE_STEP = 0,
    EXECUTION_KIND_STOP_PATH,
    EXECUTION_KIND_FAULT_PATH,
    EXECUTION_KIND_TIMEOUT_PATH
} execution_kind_t;

typedef enum {
    EXECUTION_RESULT_NONE = 0,
    EXECUTION_RESULT_ADVANCED,
    EXECUTION_RESULT_WAITING,
    EXECUTION_RESULT_COMPLETED,
    EXECUTION_RESULT_STOPPED,
    EXECUTION_RESULT_FAULTED,
    EXECUTION_RESULT_TIMED_OUT,
    EXECUTION_RESULT_IGNORED,
    EXECUTION_RESULT_REJECTED
} execution_result_t;

typedef enum {
    EXECUTION_END_REASON_NONE = 0,
    EXECUTION_END_REASON_NORMAL,
    EXECUTION_END_REASON_STOP,
    EXECUTION_END_REASON_FAULT,
    EXECUTION_END_REASON_TIMEOUT,
    EXECUTION_END_REASON_REJECTION
} execution_end_reason_t;

typedef enum {
    TRIGGER_TYPE_START = 0,
    TRIGGER_TYPE_STOP,
    TRIGGER_TYPE_DEVICE_FEEDBACK,
    TRIGGER_TYPE_FAULT,
    TRIGGER_TYPE_BUSINESS,
    TRIGGER_TYPE_TIMEOUT,
    TRIGGER_TYPE_REJECT,
    TRIGGER_TYPE_IGNORE
} trigger_type_t;

typedef enum {
    WAIT_TIMEOUT_POLICY_CONTINUE_SESSION = 0,
    WAIT_TIMEOUT_POLICY_FINISH_EXECUTION,
    WAIT_TIMEOUT_POLICY_ABORT_SESSION
} wait_timeout_policy_t;

typedef enum {
    TRANSITION_ENTITY_SESSION = 0,
    TRANSITION_ENTITY_EXECUTION,
    TRANSITION_ENTITY_REQUEST
} transition_entity_type_t;

typedef enum {
    PROGRAM_SNAPSHOT_VALIDATION_VALID = 0,
    PROGRAM_SNAPSHOT_VALIDATION_UNAVAILABLE,
    PROGRAM_SNAPSHOT_VALIDATION_INVALID
} program_snapshot_validation_t;

#endif
