#ifndef SHARED_TIMEOUTS_H
#define SHARED_TIMEOUTS_H

/**
 * @file timeouts.h
 * @brief 定义控制流程中的超时与重试常量。
 */

#define MAX_RETRY_COUNT (3)
#define MAX_WAIT_RETRY_COUNT (3)
#define MAX_PENDING_TRIGGER_COUNT (8)
#define MAX_TRIGGER_ID_LENGTH (32)
#define MAX_SIGNAL_CODE_LENGTH (64)
#define MAX_REASON_CODE_LENGTH (64)
#define PRECHECK_TIMEOUT_MS (3000)
#define MOTION_TIMEOUT_MS (15000)
#define BRUSH_TIMEOUT_MS (5000)
#define CHEMICAL_TIMEOUT_MS (5000)
#define STOP_TIMEOUT_MS (3000)
#define DEFAULT_WAIT_TIMEOUT_MS (5000)
#define DEFAULT_SEGMENT_TIMEOUT_MS (15000)
#define DEFAULT_EXIT_TIMEOUT_MS (5000)
#define CLOSE_FEEDBACK_TIMEOUT_MS (2000)
#define HOME_FEEDBACK_TIMEOUT_MS (4000)

#endif
